// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pmp.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_Running State = 0
)

var State_name = map[int32]string{
	0: "Running",
}

var State_value = map[string]int32{
	"Running": 0,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{0}
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Next                 bool     `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	B                    []byte   `protobuf:"bytes,3,opt,name=b,proto3" json:"b,omitempty"`
	Length               int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *File) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *File) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type Process struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	State                State    `protobuf:"varint,3,opt,name=state,proto3,enum=State" json:"state,omitempty"`
	IsGuard              bool     `protobuf:"varint,4,opt,name=isGuard,proto3" json:"isGuard,omitempty"`
	Assets               *Assets  `protobuf:"bytes,5,opt,name=assets,proto3" json:"assets,omitempty"`
	ExecID               int32    `protobuf:"varint,6,opt,name=execID,proto3" json:"execID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{3}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Process) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Process) GetState() State {
	if m != nil {
		return m.State
	}
	return State_Running
}

func (m *Process) GetIsGuard() bool {
	if m != nil {
		return m.IsGuard
	}
	return false
}

func (m *Process) GetAssets() *Assets {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *Process) GetExecID() int32 {
	if m != nil {
		return m.ExecID
	}
	return 0
}

type Assets struct {
	CpuUsed              float64  `protobuf:"fixed64,1,opt,name=cpuUsed,proto3" json:"cpuUsed,omitempty"`
	MemUsed              float64  `protobuf:"fixed64,2,opt,name=memUsed,proto3" json:"memUsed,omitempty"`
	DiskUsed             float64  `protobuf:"fixed64,3,opt,name=diskUsed,proto3" json:"diskUsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assets) Reset()         { *m = Assets{} }
func (m *Assets) String() string { return proto.CompactTextString(m) }
func (*Assets) ProtoMessage()    {}
func (*Assets) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{4}
}

func (m *Assets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assets.Unmarshal(m, b)
}
func (m *Assets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assets.Marshal(b, m, deterministic)
}
func (m *Assets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assets.Merge(m, src)
}
func (m *Assets) XXX_Size() int {
	return xxx_messageInfo_Assets.Size(m)
}
func (m *Assets) XXX_DiscardUnknown() {
	xxx_messageInfo_Assets.DiscardUnknown(m)
}

var xxx_messageInfo_Assets proto.InternalMessageInfo

func (m *Assets) GetCpuUsed() float64 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *Assets) GetMemUsed() float64 {
	if m != nil {
		return m.MemUsed
	}
	return 0
}

func (m *Assets) GetDiskUsed() float64 {
	if m != nil {
		return m.DiskUsed
	}
	return 0
}

type StartReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command              string   `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReq) Reset()         { *m = StartReq{} }
func (m *StartReq) String() string { return proto.CompactTextString(m) }
func (*StartReq) ProtoMessage()    {}
func (*StartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{5}
}

func (m *StartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReq.Unmarshal(m, b)
}
func (m *StartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReq.Marshal(b, m, deterministic)
}
func (m *StartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReq.Merge(m, src)
}
func (m *StartReq) XXX_Size() int {
	return xxx_messageInfo_StartReq.Size(m)
}
func (m *StartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartReq proto.InternalMessageInfo

func (m *StartReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StartReq) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

type StartResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResp) Reset()         { *m = StartResp{} }
func (m *StartResp) String() string { return proto.CompactTextString(m) }
func (*StartResp) ProtoMessage()    {}
func (*StartResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{6}
}

func (m *StartResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResp.Unmarshal(m, b)
}
func (m *StartResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResp.Marshal(b, m, deterministic)
}
func (m *StartResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResp.Merge(m, src)
}
func (m *StartResp) XXX_Size() int {
	return xxx_messageInfo_StartResp.Size(m)
}
func (m *StartResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResp.DiscardUnknown(m)
}

var xxx_messageInfo_StartResp proto.InternalMessageInfo

func (m *StartResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StopReq struct {
	ExecId               int32    `protobuf:"varint,1,opt,name=execId,proto3" json:"execId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReq) Reset()         { *m = StopReq{} }
func (m *StopReq) String() string { return proto.CompactTextString(m) }
func (*StopReq) ProtoMessage()    {}
func (*StopReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{7}
}

func (m *StopReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopReq.Unmarshal(m, b)
}
func (m *StopReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopReq.Marshal(b, m, deterministic)
}
func (m *StopReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReq.Merge(m, src)
}
func (m *StopReq) XXX_Size() int {
	return xxx_messageInfo_StopReq.Size(m)
}
func (m *StopReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReq.DiscardUnknown(m)
}

var xxx_messageInfo_StopReq proto.InternalMessageInfo

func (m *StopReq) GetExecId() int32 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

type StopResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopResp) Reset()         { *m = StopResp{} }
func (m *StopResp) String() string { return proto.CompactTextString(m) }
func (*StopResp) ProtoMessage()    {}
func (*StopResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{8}
}

func (m *StopResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopResp.Unmarshal(m, b)
}
func (m *StopResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopResp.Marshal(b, m, deterministic)
}
func (m *StopResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopResp.Merge(m, src)
}
func (m *StopResp) XXX_Size() int {
	return xxx_messageInfo_StopResp.Size(m)
}
func (m *StopResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StopResp.DiscardUnknown(m)
}

var xxx_messageInfo_StopResp proto.InternalMessageInfo

func (m *StopResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type KillReq struct {
	ExecId               int32    `protobuf:"varint,1,opt,name=execId,proto3" json:"execId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillReq) Reset()         { *m = KillReq{} }
func (m *KillReq) String() string { return proto.CompactTextString(m) }
func (*KillReq) ProtoMessage()    {}
func (*KillReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{9}
}

func (m *KillReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillReq.Unmarshal(m, b)
}
func (m *KillReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillReq.Marshal(b, m, deterministic)
}
func (m *KillReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillReq.Merge(m, src)
}
func (m *KillReq) XXX_Size() int {
	return xxx_messageInfo_KillReq.Size(m)
}
func (m *KillReq) XXX_DiscardUnknown() {
	xxx_messageInfo_KillReq.DiscardUnknown(m)
}

var xxx_messageInfo_KillReq proto.InternalMessageInfo

func (m *KillReq) GetExecId() int32 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

type KillResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillResp) Reset()         { *m = KillResp{} }
func (m *KillResp) String() string { return proto.CompactTextString(m) }
func (*KillResp) ProtoMessage()    {}
func (*KillResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{10}
}

func (m *KillResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillResp.Unmarshal(m, b)
}
func (m *KillResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillResp.Marshal(b, m, deterministic)
}
func (m *KillResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillResp.Merge(m, src)
}
func (m *KillResp) XXX_Size() int {
	return xxx_messageInfo_KillResp.Size(m)
}
func (m *KillResp) XXX_DiscardUnknown() {
	xxx_messageInfo_KillResp.DiscardUnknown(m)
}

var xxx_messageInfo_KillResp proto.InternalMessageInfo

func (m *KillResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignalReq struct {
	ExecId               int32    `protobuf:"varint,1,opt,name=execId,proto3" json:"execId,omitempty"`
	Signal               int32    `protobuf:"varint,2,opt,name=signal,proto3" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalReq) Reset()         { *m = SignalReq{} }
func (m *SignalReq) String() string { return proto.CompactTextString(m) }
func (*SignalReq) ProtoMessage()    {}
func (*SignalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{11}
}

func (m *SignalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalReq.Unmarshal(m, b)
}
func (m *SignalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalReq.Marshal(b, m, deterministic)
}
func (m *SignalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalReq.Merge(m, src)
}
func (m *SignalReq) XXX_Size() int {
	return xxx_messageInfo_SignalReq.Size(m)
}
func (m *SignalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignalReq proto.InternalMessageInfo

func (m *SignalReq) GetExecId() int32 {
	if m != nil {
		return m.ExecId
	}
	return 0
}

func (m *SignalReq) GetSignal() int32 {
	if m != nil {
		return m.Signal
	}
	return 0
}

type SignalResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalResp) Reset()         { *m = SignalResp{} }
func (m *SignalResp) String() string { return proto.CompactTextString(m) }
func (*SignalResp) ProtoMessage()    {}
func (*SignalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{12}
}

func (m *SignalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalResp.Unmarshal(m, b)
}
func (m *SignalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalResp.Marshal(b, m, deterministic)
}
func (m *SignalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalResp.Merge(m, src)
}
func (m *SignalResp) XXX_Size() int {
	return xxx_messageInfo_SignalResp.Size(m)
}
func (m *SignalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignalResp proto.InternalMessageInfo

func (m *SignalResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("State", State_name, State_value)
	proto.RegisterType((*LoginReq)(nil), "login_req")
	proto.RegisterType((*LoginResp)(nil), "login_resp")
	proto.RegisterType((*File)(nil), "file")
	proto.RegisterType((*Process)(nil), "Process")
	proto.RegisterType((*Assets)(nil), "Assets")
	proto.RegisterType((*StartReq)(nil), "Start_req")
	proto.RegisterType((*StartResp)(nil), "Start_resp")
	proto.RegisterType((*StopReq)(nil), "stop_req")
	proto.RegisterType((*StopResp)(nil), "stop_resp")
	proto.RegisterType((*KillReq)(nil), "kill_req")
	proto.RegisterType((*KillResp)(nil), "kill_resp")
	proto.RegisterType((*SignalReq)(nil), "signal_req")
	proto.RegisterType((*SignalResp)(nil), "signal_resp")
}

func init() { proto.RegisterFile("pmp.proto", fileDescriptor_609e2fa71371c143) }

var fileDescriptor_609e2fa71371c143 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x8b, 0xdb, 0x30,
	0x10, 0xc5, 0xab, 0x24, 0xfe, 0x37, 0x09, 0x25, 0x88, 0x52, 0x4c, 0x69, 0x1b, 0xa3, 0x93, 0xe9,
	0x21, 0x87, 0xf4, 0x54, 0xe8, 0xa5, 0xa5, 0x50, 0x7a, 0x29, 0x45, 0xa1, 0x50, 0x4a, 0xa1, 0x38,
	0xb6, 0xd6, 0x2b, 0x62, 0xcb, 0x5e, 0x4b, 0x81, 0x7c, 0x9c, 0xfd, 0xa8, 0x8b, 0x46, 0x72, 0xf6,
	0xe2, 0xec, 0x9e, 0x32, 0x4f, 0xf3, 0xe6, 0xa7, 0xa7, 0x8c, 0x21, 0xe9, 0xdb, 0x7e, 0xdb, 0x0f,
	0x9d, 0xe9, 0xd8, 0x06, 0x92, 0xa6, 0xab, 0xa5, 0xfa, 0x3f, 0x88, 0x3b, 0x4a, 0x61, 0xa1, 0x8a,
	0x56, 0xa4, 0x24, 0x23, 0x79, 0xc2, 0xb1, 0x66, 0xef, 0x01, 0x46, 0x83, 0xee, 0xe9, 0x1a, 0xe6,
	0xad, 0xae, 0xbd, 0xc1, 0x96, 0xec, 0x1f, 0x2c, 0x6e, 0x64, 0x23, 0xe8, 0x1b, 0x88, 0xed, 0xef,
	0xcf, 0xc7, 0xf9, 0x8b, 0x46, 0xae, 0x38, 0x9b, 0x74, 0x96, 0x91, 0x3c, 0xe6, 0x58, 0xd3, 0x15,
	0x90, 0x43, 0x3a, 0xcf, 0x48, 0xbe, 0xe2, 0xe4, 0x40, 0x5f, 0x43, 0xd8, 0x08, 0x55, 0x9b, 0xdb,
	0x74, 0x91, 0x91, 0x3c, 0xe0, 0x5e, 0xb1, 0x7b, 0x02, 0xd1, 0xaf, 0xa1, 0x2b, 0x85, 0xd6, 0x53,
	0xe9, 0x6c, 0x9e, 0x5e, 0x56, 0x08, 0x0e, 0xb8, 0x2d, 0xe9, 0x5b, 0x08, 0xb4, 0x29, 0x8c, 0x40,
	0xf6, 0xcb, 0x5d, 0xb8, 0xdd, 0x5b, 0xc5, 0xdd, 0x21, 0x4d, 0x21, 0x92, 0xfa, 0xfb, 0xa9, 0x18,
	0x2a, 0xbc, 0x28, 0xe6, 0xa3, 0xa4, 0x1b, 0x08, 0x0b, 0xad, 0x85, 0xd1, 0x69, 0x90, 0x91, 0x7c,
	0xb9, 0x8b, 0xb6, 0x5f, 0x50, 0x72, 0x7f, 0x6c, 0x23, 0x8a, 0xb3, 0x28, 0x7f, 0x7c, 0x4b, 0x43,
	0x17, 0xd1, 0x29, 0xf6, 0x07, 0x42, 0xe7, 0xb4, 0xf0, 0xb2, 0x3f, 0xfd, 0xd6, 0xa2, 0xc2, 0x8c,
	0x84, 0x8f, 0xd2, 0x76, 0x5a, 0xd1, 0x62, 0x67, 0xe6, 0x3a, 0x5e, 0xda, 0xbf, 0xad, 0x92, 0xfa,
	0x88, 0xad, 0x39, 0xb6, 0x2e, 0x9a, 0x7d, 0x82, 0x64, 0x6f, 0x8a, 0xc1, 0x5c, 0xdb, 0x0d, 0x5e,
	0xd8, 0xb5, 0x6d, 0xa1, 0x1c, 0x36, 0xe1, 0xa3, 0xb4, 0x5b, 0x1b, 0x47, 0x27, 0xb7, 0xc6, 0x20,
	0xd6, 0xa6, 0xeb, 0x91, 0x3c, 0x3e, 0xcc, 0xa5, 0x1e, 0x1f, 0x56, 0xb1, 0x77, 0x90, 0x78, 0xcf,
	0x35, 0xc4, 0x51, 0x36, 0xcd, 0x73, 0x08, 0xef, 0x99, 0x44, 0x7c, 0x06, 0xd0, 0xb2, 0x56, 0xc5,
	0x93, 0x10, 0x7b, 0xee, 0x5c, 0x7e, 0xcd, 0x5e, 0xb1, 0x0d, 0x2c, 0x2f, 0xd3, 0x53, 0xf8, 0x0f,
	0xaf, 0x20, 0xc0, 0xe5, 0xd3, 0x25, 0x44, 0xfc, 0xa4, 0x94, 0x54, 0xf5, 0xfa, 0xc5, 0x57, 0xf8,
	0x1b, 0xe3, 0xa7, 0x5f, 0x76, 0xcd, 0x21, 0xc4, 0xea, 0xe3, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x29, 0x93, 0xbc, 0x5d, 0x11, 0x03, 0x00, 0x00,
}
