// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pmp.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Signal int32

const (
	Signal_none  Signal = 0
	Signal_term  Signal = 1
	Signal_kill  Signal = 2
	Signal_user1 Signal = 3
	Signal_user2 Signal = 4
)

var Signal_name = map[int32]string{
	0: "none",
	1: "term",
	2: "kill",
	3: "user1",
	4: "user2",
}

var Signal_value = map[string]int32{
	"none":  0,
	"term":  1,
	"kill":  2,
	"user1": 3,
	"user2": 4,
}

func (x Signal) String() string {
	return proto.EnumName(Signal_name, int32(x))
}

func (Signal) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{0}
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Next                 bool     `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	B                    []byte   `protobuf:"bytes,3,opt,name=b,proto3" json:"b,omitempty"`
	Length               int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *File) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *File) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type StartReq struct {
	Args                 string   `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	ItemID               int32    `protobuf:"varint,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReq) Reset()         { *m = StartReq{} }
func (m *StartReq) String() string { return proto.CompactTextString(m) }
func (*StartReq) ProtoMessage()    {}
func (*StartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{3}
}

func (m *StartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReq.Unmarshal(m, b)
}
func (m *StartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReq.Marshal(b, m, deterministic)
}
func (m *StartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReq.Merge(m, src)
}
func (m *StartReq) XXX_Size() int {
	return xxx_messageInfo_StartReq.Size(m)
}
func (m *StartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartReq proto.InternalMessageInfo

func (m *StartReq) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *StartReq) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type StartResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResp) Reset()         { *m = StartResp{} }
func (m *StartResp) String() string { return proto.CompactTextString(m) }
func (*StartResp) ProtoMessage()    {}
func (*StartResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{4}
}

func (m *StartResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResp.Unmarshal(m, b)
}
func (m *StartResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResp.Marshal(b, m, deterministic)
}
func (m *StartResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResp.Merge(m, src)
}
func (m *StartResp) XXX_Size() int {
	return xxx_messageInfo_StartResp.Size(m)
}
func (m *StartResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResp.DiscardUnknown(m)
}

var xxx_messageInfo_StartResp proto.InternalMessageInfo

func (m *StartResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignalReq struct {
	ItemID               int32    `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Signal               Signal   `protobuf:"varint,2,opt,name=signal,proto3,enum=Signal" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalReq) Reset()         { *m = SignalReq{} }
func (m *SignalReq) String() string { return proto.CompactTextString(m) }
func (*SignalReq) ProtoMessage()    {}
func (*SignalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{5}
}

func (m *SignalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalReq.Unmarshal(m, b)
}
func (m *SignalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalReq.Marshal(b, m, deterministic)
}
func (m *SignalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalReq.Merge(m, src)
}
func (m *SignalReq) XXX_Size() int {
	return xxx_messageInfo_SignalReq.Size(m)
}
func (m *SignalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignalReq proto.InternalMessageInfo

func (m *SignalReq) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *SignalReq) GetSignal() Signal {
	if m != nil {
		return m.Signal
	}
	return Signal_none
}

type SignalResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalResp) Reset()         { *m = SignalResp{} }
func (m *SignalResp) String() string { return proto.CompactTextString(m) }
func (*SignalResp) ProtoMessage()    {}
func (*SignalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{6}
}

func (m *SignalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalResp.Unmarshal(m, b)
}
func (m *SignalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalResp.Marshal(b, m, deterministic)
}
func (m *SignalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalResp.Merge(m, src)
}
func (m *SignalResp) XXX_Size() int {
	return xxx_messageInfo_SignalResp.Size(m)
}
func (m *SignalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignalResp proto.InternalMessageInfo

func (m *SignalResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ItemInfo struct {
	ItemID               int32    `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	CpuUsed              float64  `protobuf:"fixed64,3,opt,name=cpuUsed,proto3" json:"cpuUsed,omitempty"`
	MemUsed              float64  `protobuf:"fixed64,4,opt,name=memUsed,proto3" json:"memUsed,omitempty"`
	Running              bool     `protobuf:"varint,5,opt,name=running,proto3" json:"running,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemInfo) Reset()         { *m = ItemInfo{} }
func (m *ItemInfo) String() string { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()    {}
func (*ItemInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{7}
}

func (m *ItemInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemInfo.Unmarshal(m, b)
}
func (m *ItemInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemInfo.Marshal(b, m, deterministic)
}
func (m *ItemInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemInfo.Merge(m, src)
}
func (m *ItemInfo) XXX_Size() int {
	return xxx_messageInfo_ItemInfo.Size(m)
}
func (m *ItemInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ItemInfo proto.InternalMessageInfo

func (m *ItemInfo) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *ItemInfo) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ItemInfo) GetCpuUsed() float64 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *ItemInfo) GetMemUsed() float64 {
	if m != nil {
		return m.MemUsed
	}
	return 0
}

func (m *ItemInfo) GetRunning() bool {
	if m != nil {
		return m.Running
	}
	return false
}

type SysInfo struct {
	CpuCount             int32    `protobuf:"varint,1,opt,name=cpuCount,proto3" json:"cpuCount,omitempty"`
	CpuUsedPercent       float64  `protobuf:"fixed64,2,opt,name=cpuUsedPercent,proto3" json:"cpuUsedPercent,omitempty"`
	MemTotal             string   `protobuf:"bytes,3,opt,name=memTotal,proto3" json:"memTotal,omitempty"`
	MemUsed              string   `protobuf:"bytes,4,opt,name=memUsed,proto3" json:"memUsed,omitempty"`
	MemUsedPercent       float64  `protobuf:"fixed64,5,opt,name=memUsedPercent,proto3" json:"memUsedPercent,omitempty"`
	DiskTotal            string   `protobuf:"bytes,6,opt,name=diskTotal,proto3" json:"diskTotal,omitempty"`
	DiskUsed             string   `protobuf:"bytes,7,opt,name=diskUsed,proto3" json:"diskUsed,omitempty"`
	DiskUsedPercent      float64  `protobuf:"fixed64,8,opt,name=diskUsedPercent,proto3" json:"diskUsedPercent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysInfo) Reset()         { *m = SysInfo{} }
func (m *SysInfo) String() string { return proto.CompactTextString(m) }
func (*SysInfo) ProtoMessage()    {}
func (*SysInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{8}
}

func (m *SysInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysInfo.Unmarshal(m, b)
}
func (m *SysInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysInfo.Marshal(b, m, deterministic)
}
func (m *SysInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysInfo.Merge(m, src)
}
func (m *SysInfo) XXX_Size() int {
	return xxx_messageInfo_SysInfo.Size(m)
}
func (m *SysInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SysInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SysInfo proto.InternalMessageInfo

func (m *SysInfo) GetCpuCount() int32 {
	if m != nil {
		return m.CpuCount
	}
	return 0
}

func (m *SysInfo) GetCpuUsedPercent() float64 {
	if m != nil {
		return m.CpuUsedPercent
	}
	return 0
}

func (m *SysInfo) GetMemTotal() string {
	if m != nil {
		return m.MemTotal
	}
	return ""
}

func (m *SysInfo) GetMemUsed() string {
	if m != nil {
		return m.MemUsed
	}
	return ""
}

func (m *SysInfo) GetMemUsedPercent() float64 {
	if m != nil {
		return m.MemUsedPercent
	}
	return 0
}

func (m *SysInfo) GetDiskTotal() string {
	if m != nil {
		return m.DiskTotal
	}
	return ""
}

func (m *SysInfo) GetDiskUsed() string {
	if m != nil {
		return m.DiskUsed
	}
	return ""
}

func (m *SysInfo) GetDiskUsedPercent() float64 {
	if m != nil {
		return m.DiskUsedPercent
	}
	return 0
}

type Report struct {
	Sys                  *SysInfo            `protobuf:"bytes,1,opt,name=sys,proto3" json:"sys,omitempty"`
	Items                map[int32]*ItemInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{9}
}

func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetSys() *SysInfo {
	if m != nil {
		return m.Sys
	}
	return nil
}

func (m *Report) GetItems() map[int32]*ItemInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterEnum("Signal", Signal_name, Signal_value)
	proto.RegisterType((*LoginReq)(nil), "login_req")
	proto.RegisterType((*LoginResp)(nil), "login_resp")
	proto.RegisterType((*File)(nil), "file")
	proto.RegisterType((*StartReq)(nil), "Start_req")
	proto.RegisterType((*StartResp)(nil), "Start_resp")
	proto.RegisterType((*SignalReq)(nil), "signal_req")
	proto.RegisterType((*SignalResp)(nil), "signal_resp")
	proto.RegisterType((*ItemInfo)(nil), "ItemInfo")
	proto.RegisterType((*SysInfo)(nil), "SysInfo")
	proto.RegisterType((*Report)(nil), "report")
	proto.RegisterMapType((map[int32]*ItemInfo)(nil), "report.ItemsEntry")
}

func init() { proto.RegisterFile("pmp.proto", fileDescriptor_609e2fa71371c143) }

var fileDescriptor_609e2fa71371c143 = []byte{
	// 512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x14, 0xc4, 0x4d, 0xd2, 0x26, 0xaf, 0xab, 0x12, 0xf9, 0x80, 0xa2, 0x0a, 0xd1, 0x2a, 0x87, 0x55,
	0xc4, 0x21, 0x12, 0xe5, 0x00, 0x42, 0x9c, 0x58, 0xf6, 0xb0, 0x17, 0x84, 0xbc, 0x70, 0x41, 0x48,
	0x28, 0x6d, 0xbd, 0x21, 0x6a, 0xe2, 0x04, 0x3b, 0x41, 0xf4, 0xca, 0x1f, 0xe0, 0xc0, 0x1f, 0x46,
	0xcf, 0x1f, 0x0d, 0x54, 0xcb, 0xa9, 0x33, 0x63, 0x7b, 0x66, 0xf2, 0xec, 0x42, 0xd4, 0x35, 0x5d,
	0xde, 0xc9, 0xb6, 0x6f, 0xd3, 0x15, 0x44, 0x75, 0x5b, 0x56, 0xe2, 0x8b, 0xe4, 0xdf, 0x28, 0x05,
	0x5f, 0x14, 0x0d, 0x4f, 0xc8, 0x9a, 0x64, 0x11, 0xd3, 0x38, 0x7d, 0x02, 0xe0, 0x36, 0xa8, 0x8e,
	0xc6, 0xe0, 0x35, 0xaa, 0xb4, 0x1b, 0x10, 0xa6, 0x9f, 0xc1, 0xbf, 0xab, 0x6a, 0x4e, 0x97, 0x10,
	0xe2, 0xef, 0xbb, 0xf1, 0xfc, 0x89, 0x6b, 0x5f, 0xfe, 0xa3, 0x4f, 0x26, 0x6b, 0x92, 0x85, 0x4c,
	0x63, 0x7a, 0x01, 0x64, 0x9b, 0x78, 0x6b, 0x92, 0x5d, 0x30, 0xb2, 0xa5, 0x8f, 0x60, 0x5a, 0x73,
	0x51, 0xf6, 0x5f, 0x13, 0x7f, 0x4d, 0xb2, 0x80, 0x59, 0x96, 0xbe, 0x80, 0xe8, 0xb6, 0x2f, 0x64,
	0xef, 0xea, 0x15, 0xb2, 0x54, 0xae, 0x1e, 0x62, 0x3c, 0x58, 0xf5, 0xbc, 0xb9, 0x79, 0xab, 0xcd,
	0x03, 0x66, 0x19, 0xd6, 0x76, 0x07, 0xef, 0xad, 0x7d, 0x0d, 0xa0, 0xaa, 0x52, 0x14, 0xb5, 0x76,
	0x1e, 0x5d, 0xc8, 0xdf, 0x2e, 0x74, 0x05, 0x53, 0xb3, 0x4b, 0xbb, 0x2f, 0x36, 0xb3, 0xdc, 0x50,
	0x66, 0xe5, 0x74, 0x05, 0xf3, 0x93, 0xcd, 0xbd, 0x39, 0x3f, 0x09, 0x84, 0x37, 0x68, 0x26, 0xee,
	0xda, 0xff, 0xc6, 0xc4, 0xe0, 0x75, 0xd5, 0xde, 0x7e, 0x01, 0x42, 0x9a, 0xc0, 0x6c, 0xd7, 0x0d,
	0x1f, 0x15, 0xdf, 0xeb, 0x19, 0x11, 0xe6, 0x28, 0xae, 0x34, 0xbc, 0xd1, 0x2b, 0xbe, 0x59, 0xb1,
	0x14, 0x57, 0xe4, 0x20, 0x44, 0x25, 0xca, 0x24, 0xd0, 0x83, 0x76, 0x34, 0xfd, 0x35, 0x81, 0xd9,
	0xed, 0x51, 0xe9, 0x0e, 0x4b, 0x08, 0x77, 0xdd, 0x70, 0xd5, 0x0e, 0xa2, 0xb7, 0x2d, 0x4e, 0x9c,
	0x5e, 0xc2, 0xc2, 0xc6, 0xbc, 0xe7, 0x72, 0xc7, 0x85, 0xb9, 0x31, 0xc2, 0xce, 0x54, 0xf4, 0x68,
	0x78, 0xf3, 0xa1, 0xed, 0x8b, 0x5a, 0xd7, 0x8b, 0xd8, 0x89, 0x9f, 0xf7, 0x8b, 0xc6, 0x7e, 0x97,
	0xb0, 0xb0, 0xd0, 0xb9, 0x07, 0xc6, 0xfd, 0x5f, 0x95, 0x3e, 0x86, 0x68, 0x5f, 0xa9, 0x83, 0xb1,
	0x9f, 0x6a, 0x8f, 0x51, 0xc0, 0x6c, 0x24, 0x3a, 0x60, 0x66, 0xb2, 0x1d, 0xa7, 0x19, 0x3c, 0x74,
	0xd8, 0x45, 0x84, 0x3a, 0xe2, 0x5c, 0x4e, 0x7f, 0x13, 0x98, 0x4a, 0xde, 0xb5, 0x12, 0x3f, 0xc6,
	0x53, 0x47, 0xf3, 0xa8, 0xe6, 0x9b, 0x30, 0xb7, 0x73, 0x62, 0x28, 0xd2, 0x0c, 0x02, 0xbc, 0x22,
	0x95, 0x4c, 0xd6, 0x5e, 0x36, 0xdf, 0xd0, 0xdc, 0x9c, 0xc9, 0xf1, 0x46, 0xd5, 0xb5, 0xe8, 0xe5,
	0x91, 0x99, 0x0d, 0xcb, 0x2b, 0x80, 0x51, 0xc4, 0x0b, 0x3d, 0xf0, 0xa3, 0x9d, 0x2f, 0x42, 0xba,
	0x82, 0xe0, 0x7b, 0x51, 0x0f, 0x5c, 0x4f, 0x74, 0xbe, 0x89, 0x72, 0xf7, 0x28, 0x98, 0xd1, 0x5f,
	0x4d, 0x5e, 0x92, 0xa7, 0xaf, 0xdd, 0x73, 0xa3, 0x21, 0xf8, 0xa2, 0x15, 0x3c, 0x7e, 0x80, 0xa8,
	0xe7, 0xb2, 0x89, 0x09, 0xa2, 0x43, 0x55, 0xd7, 0xf1, 0x84, 0x46, 0x10, 0x0c, 0x8a, 0xcb, 0x67,
	0xb1, 0xe7, 0xe0, 0x26, 0xf6, 0xdf, 0xc0, 0xa7, 0x50, 0xff, 0xa7, 0x77, 0x6d, 0xbd, 0x9d, 0x6a,
	0xf4, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x75, 0x46, 0x99, 0xea, 0x03, 0x00, 0x00,
}
