// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pmp.proto

package protocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type State int32

const (
	State_Running State = 0
)

var State_name = map[int32]string{
	0: "Running",
}

var State_value = map[string]int32{
	"Running": 0,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}

func (State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{0}
}

type Signal int32

const (
	Signal_none  Signal = 0
	Signal_term  Signal = 1
	Signal_kill  Signal = 2
	Signal_user1 Signal = 3
	Signal_user2 Signal = 4
)

var Signal_name = map[int32]string{
	0: "none",
	1: "term",
	2: "kill",
	3: "user1",
	4: "user2",
}

var Signal_value = map[string]int32{
	"none":  0,
	"term":  1,
	"kill":  2,
	"user1": 3,
	"user2": 4,
}

func (x Signal) String() string {
	return proto.EnumName(Signal_name, int32(x))
}

func (Signal) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{1}
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResp) Reset()         { *m = LoginResp{} }
func (m *LoginResp) String() string { return proto.CompactTextString(m) }
func (*LoginResp) ProtoMessage()    {}
func (*LoginResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{1}
}

func (m *LoginResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResp.Unmarshal(m, b)
}
func (m *LoginResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResp.Marshal(b, m, deterministic)
}
func (m *LoginResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResp.Merge(m, src)
}
func (m *LoginResp) XXX_Size() int {
	return xxx_messageInfo_LoginResp.Size(m)
}
func (m *LoginResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResp proto.InternalMessageInfo

func (m *LoginResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type File struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Next                 bool     `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
	B                    []byte   `protobuf:"bytes,3,opt,name=b,proto3" json:"b,omitempty"`
	Length               int32    `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{2}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *File) GetNext() bool {
	if m != nil {
		return m.Next
	}
	return false
}

func (m *File) GetB() []byte {
	if m != nil {
		return m.B
	}
	return nil
}

func (m *File) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

type Process struct {
	ItemID               int32    `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	State                State    `protobuf:"varint,3,opt,name=state,proto3,enum=State" json:"state,omitempty"`
	IsGuard              bool     `protobuf:"varint,4,opt,name=isGuard,proto3" json:"isGuard,omitempty"`
	Assets               *Assets  `protobuf:"bytes,5,opt,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Process) Reset()         { *m = Process{} }
func (m *Process) String() string { return proto.CompactTextString(m) }
func (*Process) ProtoMessage()    {}
func (*Process) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{3}
}

func (m *Process) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Process.Unmarshal(m, b)
}
func (m *Process) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Process.Marshal(b, m, deterministic)
}
func (m *Process) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Process.Merge(m, src)
}
func (m *Process) XXX_Size() int {
	return xxx_messageInfo_Process.Size(m)
}
func (m *Process) XXX_DiscardUnknown() {
	xxx_messageInfo_Process.DiscardUnknown(m)
}

var xxx_messageInfo_Process proto.InternalMessageInfo

func (m *Process) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *Process) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Process) GetState() State {
	if m != nil {
		return m.State
	}
	return State_Running
}

func (m *Process) GetIsGuard() bool {
	if m != nil {
		return m.IsGuard
	}
	return false
}

func (m *Process) GetAssets() *Assets {
	if m != nil {
		return m.Assets
	}
	return nil
}

type Assets struct {
	CpuUsed              float64  `protobuf:"fixed64,1,opt,name=cpuUsed,proto3" json:"cpuUsed,omitempty"`
	MemUsed              float64  `protobuf:"fixed64,2,opt,name=memUsed,proto3" json:"memUsed,omitempty"`
	DiskUsed             float64  `protobuf:"fixed64,3,opt,name=diskUsed,proto3" json:"diskUsed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Assets) Reset()         { *m = Assets{} }
func (m *Assets) String() string { return proto.CompactTextString(m) }
func (*Assets) ProtoMessage()    {}
func (*Assets) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{4}
}

func (m *Assets) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Assets.Unmarshal(m, b)
}
func (m *Assets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Assets.Marshal(b, m, deterministic)
}
func (m *Assets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Assets.Merge(m, src)
}
func (m *Assets) XXX_Size() int {
	return xxx_messageInfo_Assets.Size(m)
}
func (m *Assets) XXX_DiscardUnknown() {
	xxx_messageInfo_Assets.DiscardUnknown(m)
}

var xxx_messageInfo_Assets proto.InternalMessageInfo

func (m *Assets) GetCpuUsed() float64 {
	if m != nil {
		return m.CpuUsed
	}
	return 0
}

func (m *Assets) GetMemUsed() float64 {
	if m != nil {
		return m.MemUsed
	}
	return 0
}

func (m *Assets) GetDiskUsed() float64 {
	if m != nil {
		return m.DiskUsed
	}
	return 0
}

type StartReq struct {
	Args                 string   `protobuf:"bytes,1,opt,name=args,proto3" json:"args,omitempty"`
	ItemID               int32    `protobuf:"varint,2,opt,name=itemID,proto3" json:"itemID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartReq) Reset()         { *m = StartReq{} }
func (m *StartReq) String() string { return proto.CompactTextString(m) }
func (*StartReq) ProtoMessage()    {}
func (*StartReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{5}
}

func (m *StartReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartReq.Unmarshal(m, b)
}
func (m *StartReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartReq.Marshal(b, m, deterministic)
}
func (m *StartReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartReq.Merge(m, src)
}
func (m *StartReq) XXX_Size() int {
	return xxx_messageInfo_StartReq.Size(m)
}
func (m *StartReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StartReq.DiscardUnknown(m)
}

var xxx_messageInfo_StartReq proto.InternalMessageInfo

func (m *StartReq) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

func (m *StartReq) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

type StartResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartResp) Reset()         { *m = StartResp{} }
func (m *StartResp) String() string { return proto.CompactTextString(m) }
func (*StartResp) ProtoMessage()    {}
func (*StartResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{6}
}

func (m *StartResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartResp.Unmarshal(m, b)
}
func (m *StartResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartResp.Marshal(b, m, deterministic)
}
func (m *StartResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartResp.Merge(m, src)
}
func (m *StartResp) XXX_Size() int {
	return xxx_messageInfo_StartResp.Size(m)
}
func (m *StartResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StartResp.DiscardUnknown(m)
}

var xxx_messageInfo_StartResp proto.InternalMessageInfo

func (m *StartResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignalReq struct {
	ItemID               int32    `protobuf:"varint,1,opt,name=itemID,proto3" json:"itemID,omitempty"`
	Signal               Signal   `protobuf:"varint,2,opt,name=signal,proto3,enum=Signal" json:"signal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalReq) Reset()         { *m = SignalReq{} }
func (m *SignalReq) String() string { return proto.CompactTextString(m) }
func (*SignalReq) ProtoMessage()    {}
func (*SignalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{7}
}

func (m *SignalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalReq.Unmarshal(m, b)
}
func (m *SignalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalReq.Marshal(b, m, deterministic)
}
func (m *SignalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalReq.Merge(m, src)
}
func (m *SignalReq) XXX_Size() int {
	return xxx_messageInfo_SignalReq.Size(m)
}
func (m *SignalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalReq.DiscardUnknown(m)
}

var xxx_messageInfo_SignalReq proto.InternalMessageInfo

func (m *SignalReq) GetItemID() int32 {
	if m != nil {
		return m.ItemID
	}
	return 0
}

func (m *SignalReq) GetSignal() Signal {
	if m != nil {
		return m.Signal
	}
	return Signal_none
}

type SignalResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignalResp) Reset()         { *m = SignalResp{} }
func (m *SignalResp) String() string { return proto.CompactTextString(m) }
func (*SignalResp) ProtoMessage()    {}
func (*SignalResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_609e2fa71371c143, []int{8}
}

func (m *SignalResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalResp.Unmarshal(m, b)
}
func (m *SignalResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalResp.Marshal(b, m, deterministic)
}
func (m *SignalResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalResp.Merge(m, src)
}
func (m *SignalResp) XXX_Size() int {
	return xxx_messageInfo_SignalResp.Size(m)
}
func (m *SignalResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalResp.DiscardUnknown(m)
}

var xxx_messageInfo_SignalResp proto.InternalMessageInfo

func (m *SignalResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterEnum("State", State_name, State_value)
	proto.RegisterEnum("Signal", Signal_name, Signal_value)
	proto.RegisterType((*LoginReq)(nil), "login_req")
	proto.RegisterType((*LoginResp)(nil), "login_resp")
	proto.RegisterType((*File)(nil), "file")
	proto.RegisterType((*Process)(nil), "Process")
	proto.RegisterType((*Assets)(nil), "Assets")
	proto.RegisterType((*StartReq)(nil), "Start_req")
	proto.RegisterType((*StartResp)(nil), "Start_resp")
	proto.RegisterType((*SignalReq)(nil), "signal_req")
	proto.RegisterType((*SignalResp)(nil), "signal_resp")
}

func init() { proto.RegisterFile("pmp.proto", fileDescriptor_609e2fa71371c143) }

var fileDescriptor_609e2fa71371c143 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0x4f, 0x8b, 0xd5, 0x30,
	0x14, 0xc5, 0x27, 0xfd, 0xdf, 0xfb, 0x86, 0xa1, 0x04, 0x91, 0x22, 0x62, 0x4b, 0x57, 0x65, 0x16,
	0x05, 0xeb, 0xc2, 0x8d, 0x1b, 0x45, 0x11, 0x37, 0x22, 0x19, 0x04, 0x11, 0x41, 0xfa, 0x5e, 0x63,
	0x0d, 0xd3, 0xa6, 0x35, 0x49, 0xc1, 0x0f, 0xe1, 0x87, 0x96, 0xdc, 0x36, 0xcf, 0x59, 0x3c, 0x57,
	0x3d, 0xbf, 0x7b, 0x6e, 0x4e, 0xfe, 0xdc, 0x42, 0xba, 0x4c, 0x4b, 0xb3, 0xa8, 0xd9, 0xcc, 0x55,
	0x01, 0xe9, 0x38, 0x0f, 0x42, 0x7e, 0x57, 0xfc, 0x17, 0xa5, 0x10, 0xc8, 0x6e, 0xe2, 0x39, 0x29,
	0x49, 0x9d, 0x32, 0xd4, 0xd5, 0x33, 0x00, 0xd7, 0xa0, 0x17, 0x9a, 0x81, 0x3f, 0xe9, 0x61, 0x6f,
	0xb0, 0xb2, 0xfa, 0x06, 0xc1, 0x0f, 0x31, 0x72, 0xfa, 0x04, 0x12, 0xfb, 0xfd, 0xf8, 0x6f, 0xfd,
	0x99, 0x31, 0x97, 0xff, 0x36, 0xb9, 0x57, 0x92, 0x3a, 0x61, 0xa8, 0xe9, 0x35, 0x90, 0x63, 0xee,
	0x97, 0xa4, 0xbe, 0x66, 0xe4, 0x48, 0x1f, 0x43, 0x34, 0x72, 0x39, 0x98, 0x9f, 0x79, 0x50, 0x92,
	0x3a, 0x64, 0x3b, 0x55, 0x7f, 0x08, 0xc4, 0x9f, 0xd4, 0x7c, 0xe2, 0x5a, 0xdb, 0x1e, 0x61, 0xf8,
	0xf4, 0xe1, 0x2d, 0xe6, 0x87, 0x6c, 0x27, 0x7b, 0xa6, 0x45, 0xf4, 0x18, 0x1e, 0x32, 0x2b, 0xe9,
	0x53, 0x08, 0xb5, 0xe9, 0x0c, 0xc7, 0xfc, 0x9b, 0x36, 0x6a, 0xee, 0x2c, 0xb1, 0xad, 0x48, 0x73,
	0x88, 0x85, 0x7e, 0xbf, 0x76, 0xaa, 0xc7, 0xcd, 0x12, 0xe6, 0x90, 0x16, 0x10, 0x75, 0x5a, 0x73,
	0xa3, 0xf3, 0xb0, 0x24, 0xf5, 0xa1, 0x8d, 0x9b, 0xd7, 0x88, 0x6c, 0x2f, 0x57, 0x5f, 0x20, 0xda,
	0x2a, 0x36, 0xe4, 0xb4, 0xac, 0x9f, 0x35, 0xef, 0xf1, 0x34, 0x84, 0x39, 0xb4, 0xce, 0xc4, 0x27,
	0x74, 0xbc, 0xcd, 0xd9, 0xd1, 0x3e, 0x51, 0x2f, 0xf4, 0x3d, 0x5a, 0x3e, 0x5a, 0x67, 0xae, 0x5e,
	0x42, 0x7a, 0x67, 0x3a, 0x65, 0xdc, 0x1c, 0x3a, 0x35, 0x68, 0x37, 0x07, 0xab, 0x1f, 0xdc, 0xde,
	0x7b, 0x78, 0x7b, 0x3b, 0x1f, 0xb7, 0xf0, 0xe2, 0x7c, 0xde, 0x01, 0x68, 0x31, 0xc8, 0x6e, 0xc4,
	0xe4, 0xff, 0xbd, 0x61, 0x01, 0xd1, 0xd6, 0x85, 0xe9, 0x37, 0x6d, 0xdc, 0x6c, 0xc8, 0xf6, 0x72,
	0x55, 0xc0, 0xe1, 0x1c, 0x73, 0x69, 0x9f, 0xdb, 0x47, 0x10, 0xe2, 0x2b, 0xd3, 0x03, 0xc4, 0x6c,
	0x95, 0x52, 0xc8, 0x21, 0xbb, 0xba, 0x7d, 0xe5, 0x72, 0x69, 0x02, 0x81, 0x9c, 0x25, 0xcf, 0xae,
	0xac, 0x32, 0x5c, 0x4d, 0x19, 0xb1, 0xea, 0x5e, 0x8c, 0x63, 0xe6, 0xd1, 0x14, 0xc2, 0x55, 0x73,
	0xf5, 0x3c, 0xf3, 0x9d, 0x6c, 0xb3, 0xe0, 0x0d, 0x7c, 0x4d, 0xf0, 0x2f, 0x3d, 0xcd, 0xe3, 0x31,
	0x42, 0xf5, 0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x03, 0x0f, 0x66, 0xbc, 0x02, 0x00,
	0x00,
}
